project_name: bannerscanner
release:
  github:
    owner: JustinAzoff
    name: bannerscanner
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - linux_amd64
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: bannerscanner
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpm:
  description: Simple TCP Port scanner and banner grabber that outputs JSON
  license: MIT
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/bin
  homepage: https://github.com/JustinAzoff/bannerscanner
  maintainer: Justin Azoff <justin@bouncybouncy.net>
  formats:
    - deb
    - rpm
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
